url: 
baseurl: "" 

index:
  en:
  ca: index_ca.html

# Site settings
title: Col·lectivaT
email: info@collectivat.cat
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
header:
  intro_sub:
    en: "Col·lectivaT is a non-profit cooperative formed by knowledge workers that provides services of cultural translation, research and technological services for collaborative and linguistic work.
To provide an all-around service, our work is based on three main axes: Language, Technology, Research and consultancy. The linguistic axis seeks to overcome language barriers, therefore, communication and access to information -for now- about Turkey and Kurdistan. The technological axis provides the necessary infrastructure for language work and facilitates repetitive tasks in this work, such as transcription or subtitling; and lastly, the consultation axis includes cultural translation jobs that respond to the demands of the most elaborate deep activities such as academic or journalistic research on the area."
    ca: "Col·lectivaT és una cooperativa sense ànim de lucre formada per les treballadores de coneixement que proporciona serveis de traducció cultural, de recerca i serveis tecnològics per treball col·laboratiu i lingüístic. Per un servei integral, el nostre treball es basa en tres eixos principals: Llengua, Tecnologia, Recerca i consultoria. L’eix lingüístic pretén superar les barreres de llengua, per tant, la comunicació i l’accés a la informació -per ara- sobre Turquia i Kurdistan. L'eix tecnològic proporciona la infraestructura necessària per feines lingüístiques i facilitar tasques repetitives en aquesta feina, com la transcripció o la subtitulació; i per últim, l'eix de consultaria inclou feines de traducció cultural que respon a les demandes de les activitats més profundes com la recerca acadèmica o periodística sobre la zona."

  intro:
    en:
    ca:
  services:
    en: Services
    ca: Serveis
  portfolio:
    en: Portfolio
    ca: Portfolio
  about:
    en: About
    ca: Sobre Nosaltres
  team:
    en: Team
    ca: L'equip
  contact:
    en: Contact
    ca: Contacte

# Services text
services:
  intro:
    en: We use our cultural knowledge and technological know-how to help your organization achive efficiency and tackle cultural barriers.
    ca: Utilitzem els nostres coneixements culturals i els coneixements tecnològics per ajudar a la vostra organització a assolir eficients.
  list:
    - name:
        en: Productivity Stack
        ca: Productivitat
      description:
        en: We offer ''data sovereing'' alternatives to the digital infrastructure you need, to build your business upon. Be it productivity tools like collaborative document editing, online calendar and file sharing or marketing tools like web analytics, resource planning and customer relations platforms; we setup and deliver your self-hosted open source applications to increase your productivity.
        ca: Oferim alternatives de ''sobiranes'' a la infraestructura digital que necessiteu, per construir-ne el negoci. Sigui eines de productivitat com l'edició de documents col·laboratius, el calendari en línia i l'ús compartit de fitxers o eines de màrqueting, com ara l'anàlisi web, la planificació de recursos i les plataformes de relació amb els clients; configurem i lliurem les aplicacions de codi obert allotjades per autosuficients per augmentar la seva productivitat.
      fa_icon: fa-calendar
    - name:
        en: Language Services
        ca: Serveis Lingüístics
      description:
        en: We are one of the very few organizations who can translate between catalan and turkish both directions, without the use of a bridge language. We ensure the correctness of our work with the cultural knowledge of both worlds, effectively enriching them. Thanks to our strong technological branch, we are able to work with any file format. We develop new and revolutionary ways of doing subtitling using the state-of-the-art open technologies for audio processing, computer aided translation and collective work.
        ca: Som una de les poques organitzacions que poden traduir entre català i turc ambdós sentits, sense utilitzar un llenguatge pont. Garantim la correcció del nostre treball amb el coneixement cultural d'ambdós mons, enriquint-los amb eficàcia. Gràcies a la nostra forta branca tecnològica, podem treballar amb qualsevol format de fitxer. Desenvolupem formes noves i revolucionàries de subtitulació utilitzant les tecnologies obertes de l'última generació per al processament d'àudio, la traducció assistida per ordinador i el treball col·lectiu.
      fa_icon: fa-language
    - name:
        en: Socio-Cultural Research and Consulting
        ca: Recerca i Consultoria Sociocultural
      description:
        en: We are social scientists who actively work on Turkey/Kurdistan and Spain/Catalunya. We provide consulting for researchers, journalist or NGOs to prepare and manage their projects in the zone. We put you in contact with the key networks, organize the logistics if necessary, lifting the cultural and contextual boundaries so that your organization can focus on the impact and successful execution of your project. We setup your data infrasructure, facilitate access to it and enable its monitorization with visualizations and dashboards. We provide you with the tools to structure your information, and to protect/save your organizational memory.
        ca: Som científics socials ı treballem activament a Turquia / Kurdistan i Espanya / Catalunya. Proporcionem assessorament a investigadors, periodistes o ONG per preparar i gestionar els seus projectes a la zona. Ens posem en contacte amb les xarxes clau, organitzem la logística si és necessari, aixecant els límits culturals i contextuals perquè la vostra organització pugui centrar-se en l'impacte i la correcta execució del projecte. Configurem la infraestructura de dades, facilitem l'accés i habilitem la seva monitorització amb visualitzacions i panells de dades. Us oferim les eines per estructurar la vostra informació i protegir / desar la memòria de l'organització.
      fa_icon: fa-bar-chart-o

portfolio:
  intro:
    en: How do we help organizations in practice.
    ca: Com ajudem a les organitzacions a la pràctica.

# About text
about:
  intro:
    en: "We are a non-profit cooperative of Catalunya and in addition to the cooperative principles we hold also these values in dear:"
    ca: "Som una cooperativa sense ànim de lucre de Catalunya i, a més dels principis cooperatius, tenim també aquests valors en estimats:"
  list:
    - row:
        - name:
            en: Self-empowerment 
            ca: Auto-enfortiment
          description:
            en: We believe that self-empowerment is the key in de-centralization of tasks and effective decision making. Through it, we strive for autonomy within our organization and also the autonomy of our partners in everything they do. This also entails technological sovereignty, i.e. the independence from proprietary software or technological services that are close, and also freedom from monopolistic knowledge channels.
            ca: Creiem que l'autodeterminació és la clau en la descentralització de tasques i en la presa de decisions efectives. A través d'ell, ens esforcem per l'autonomia dins de la nostra organització i també per l'autonomia dels nostres socis en tot el que fan. Això també implica la sobirania tecnològica, és a dir, la independència de programari propietari o serveis tecnològics que estan a prop, i també la llibertat dels canals de coneixement monopolístics.
          fa_icon: fa-hand-rock-o
        - name:
            en: Critical thinking
            ca: Pensament crític
          description:
            en: We believe that in order to provide our clients with the best and the most accurate information, we need to be critical not only with the mainstream information and practices, but also we need to be self-critical with ourselves and our work to aspire for better service for our partners.
            ca: Creiem que per proporcionar als nostres clients la millor i més precisa informació, hem de ser crítics no només amb la informació i pràctiques principals, sinó que també hem de ser autocrítics amb nosaltres mateixos i amb la nostra feina per aspirar a millorar servei per als nostres socis.
          fa_icon: fa-bomb
        - name:
            en: Interdisciplinarity
            ca: Interdisciplinarietat
          description:
            en: We are firmly dedicated to providing integral services to our partners. This necessitates an environment which professionals from different disciplines can collaborate with ease. As a collective we are dedicated to provide the existence of a type of environment which facilitates this type of interdisciplinary development.
            ca: Estem fermament dedicats a proporcionar serveis integrals als nostres socis. Això requereix un entorn que els professionals de diferents disciplines puguin col·laborar amb facilitat. Com a col·lectiu, ens dediquem a proporcionar l'existència d'un tipus d'entorn que faciliti aquest tipus de desenvolupament interdisciplinari.
          fa_icon: fa-cogs
    - row:
        - name:
            en: Empathy
            ca: Empatia
          description:
            en: We believe that competitive practices of the market infect the work practices and internal culture of organizations. However in order to provide the best service experience, understanding the needs of one’s partners should have the utmost importance. Our willingness to put ourselves in the shoes of our partners and colleagues set us apart.
            ca: Creiem que les pràctiques competitives del mercat infecten les pràctiques laborals i la cultura interna de les organitzacions. No obstant això, per tal de proporcionar la millor experiència en el servei, la comprensió de les necessitats dels socis hauria de tenir la màxima importància. La nostra voluntat de posar-nos a la pell dels nostres socis i companys ens separava.
          fa_icon: fa-comments
        - name:
            en: Reverse hierarchy
            ca: Jerarquia inversa
          description:
            en: We know that the person who is the main practitioner of a task has the best insight on it. That is why we believe that the person who will eventually do the work should have the last word over the admission or the execution of that task, and the rest of the members cannot oblige a colleague to undertake a project.
            ca: Sabem que la persona que és la principal practicant d'una tasca té la millor informació sobre això. Per això, creiem que la persona que finalment farà el treball hauria de tenir l'última paraula sobre l'admissió o l'execució d'aquesta tasca, i la resta dels membres no poden obligar un col·lega a emprendre un projecte.
          fa_icon: fa-group
        - name: 
            en: Protection of the commons
            ca: Pro communs
          description:
            en: We are dedicated to create and maintain resources which are common to a community of knowledge workers. We take part in community driven projects whether it be informing the public through creation of open data repositories or development of free and open source tools.
            ca: Ens dediquem a crear i mantenir recursos que són comuns a una comunitat de treballadors del coneixement. Participem en projectes dirigits per la comunitat ja sigui per informar al públic mitjançant la creació de repositoris de dades oberts o el desenvolupament d'eines de codi obert i lliure.
          fa_icon: fa-globe



# Team names, titles and social links
people:
  intro:
    en: We value interdisciplinary work and our expertise in diverse areas shows.
    ca: Valorem el treball interdisciplinari i la nostra experiència en diversos àmbits. 
  list:
    - name: Özgür Güneş Öztürk Okumuş
      pic: 1
      position:
        en: Dynamizer of Research and Consulting
        ca: La Dinamitzadora de Recerca i Consultoria
      social:
        - title: twitter
          url: #
        - title: stack-overflow
          url: #
    - name: Pelin Doğan
      pic: 2
      position:
        en: Dynamizer of Language Services
        ca: La Dinamitzadora dels Serveis Lingüístics
      social:
        - title: twitter
          url: #
        - title: linkedin
          url: #
    - name: Baybars Külebi
      pic: 3
      position:
        en: Dynamizer of Technology
        ca: El Dinamitzador de Tecnologia
      social:
        - title: twitter
          url: #
        - title: facebook
          url: #
    - name: Federica Capranico
      pic: 4
      position:
        en: Business Intelligence Expert
        ca: Business Intelligence Expert
      social:
        - title: twitter
          url: #
        - title: facebook
          url: #
    - name: Alp Öktem
      pic: 5
      position:
        en: Computational Linguistics Expert
        ca: Computational Linguistics Expert
      social:
        - title: twitter
          url: #
        - title: facebook
          url: #
  footer:
    en: We also collaborate with many other professionals, not only in Catalunya but also in Turkey.
    ca: També col·laborem amb molts altres professionals, no només a Catalunya, sinó també a Turquia.

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/collectivat
  - title: facebook
    url:
  #- title: stack-overflow
  #  url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/collectivat
  - title: github
    url: http://github.com/collectivat

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
